### ISSUE TITLE
1.20 Support

### ISSUE THREAD

**Issue by jacobjake1** [TrollsterCooleg/ExplosionResist#1]
I know this project is kinda dead but it'd be amazing if you could update to 1.20

**Comment by TrollsterCooleg** [comment]
1.20.5+ support on paper would likely be pretty easy to do, I might do that, but other 1.20 versions seem silly to update for since they arent even latest at this point

**Comment by jacobjake1** [comment]
I can't update because most plugins don't support 1.20.5 and above yet

**Comment by TrollsterCooleg** [comment]
Is there any specific version you need it to work for then?

**Comment by jacobjake1** [comment]
1.20.1 perferably, but I might be able to get 1.20.4 to work

**Comment by jacobjake1** [comment]
I'm on 1.20.4 now if you could update to that

**Comment by TrollsterCooleg** [comment]
Should be functional on 1.20.4 now, please download from the github releases.

https://github.com/TrollsterCooleg/ExplosionResist/releases/tag/v1.1
